### ISSUE TITLE
Setup dialog broken

### ISSUE THREAD

**Issue by bigboban** [pnbruckner/ha-life360#16]
Setup dialog is somehow broken 

![image](https://github.com/pnbruckner/ha-life360/assets/7159224/f89c74fb-4e8a-491a-99e9-2c6432cdc0e0)

**Comment by pnbruckner** [comment]
Can you try force refreshing your browser, e.g., Ctrl-F5?

If that doesn't work, then...
Did you have an older version of the Life360 integration installed, and if so, which version?
What language do you have selected for your user profile?

**Comment by UplandJacob** [comment]
That happened to me the other days too. I updated to the latest release and it worked fine. The release probably didn’t make a difference though. 

Btw it has been working for a couple of days straight now (instead of working for a couple of hours then stopping), so good job fixing all this nonsense!

**Comment by bigboban** [comment]
It is ok now. Maybe after browser restart..
