### ISSUE TITLE
Life 360 plugin locates me home randomly but i am not at home

### ISSUE THREAD

**Issue by bigboban** [pnbruckner/ha-life360#32]
I think this may be similar problem like https://github.com/home-assistant/core/issues/122081.

Description from life360 view:

- I have HA instance (second on weekend house, but i think this is not interesting here)
- This instance has some GPS coordinates in global settings.
- Life 360 zone (defined in app) on this place has name "weekend house" for example
- Life 360 app shows  "weekend house" and it is right and this information is stable all time i came here in life 360 app.
- BUT - HA life 360 tracker switches randomly between "home" and "weekend house"

My theory is, when life 360 says "weekend zone" integration obey it and show "weekend". But when GPS coordinate exactly match HA "home" zone it switches to "home". And back and forth forever and randomly.

![image](https://github.com/user-attachments/assets/50f8fea6-aa30-403e-8315-d9cfa94df3bb)

I think Life 360 should obey Life 360 server/app zone name.

For linked issue it is little bit different because from "HA server" point of view i am "home" and "weekend" together. But Life 360 should ignore HA "home" coordinates and use only life 360 server info.

I hope it is clear and i am convinced this is life 360 integration bug.

**Comment by pnbruckner** [comment]
What versions of the Life360 integration and HA are you using?

In general, the Life360 integration does not decide what the `device_tracker` entity's state is. The only exception to that is when location information is not available (from the Life360 server, such as when the member is not sharing their location) it sets the state to `unknown`, and when "show state as driving" is enabled, and the speed is at or above the driving speed threshold, and the entity is not in a HA zone, then it sets the state to `driving`.

Normally, and by design, the entity's state is decided by HA's "component level" code; in this case, the `device_tracker` component code. It bases this on several things, but for GPS based integrations (like Life360), it bases it on the GPS coordinates and HA zones. When it determines the entity's "accuracy" circle overlaps the circle defined by the HA instance's "home" coordinates & radius, then it sets the state to `home`.

How `home` is shown in the UI is another story. I'm not entirely sure how that works. It may be a simple translation of the word "home", or it may use the name of the HA instance. I don't really know. But more to the point, that is not decided by the Life360 integration.

**Comment by bigboban** [comment]
I understand. So it is really the same problem as https://github.com/home-assistant/core/issues/122081. I think it is rea bug but i have no reply on that ticket. :-(
